EC2Instance:
  Type: AWS::EC2::Instance
  Properties:
    AvailabilityZone: us-east-1a
    ImageId: ami-0b5eea76982371e91
    KeyName: !Ref KeyName
    InstanceType: t2.micro
    SecurityGroups:
      - !Ref Ec2SecurityGroup
